# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: G:/Vivado/Pynq_file/PYNQ-master/boards/Pynq-Z2/base/vivado/constraints/base.xdc

# Block Designs: bd/base/base.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base || ORIG_REF_NAME==base} -quiet] -quiet

# IP: bd/base/ip/base_audio_codec_ctrl_0_0/base_audio_codec_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_audio_codec_ctrl_0_0 || ORIG_REF_NAME==base_audio_codec_ctrl_0_0} -quiet] -quiet

# IP: bd/base/ip/base_btns_gpio_0/base_btns_gpio_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_btns_gpio_0 || ORIG_REF_NAME==base_btns_gpio_0} -quiet] -quiet

# IP: bd/base/ip/base_clk_wiz_10MHz_0/base_clk_wiz_10MHz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_clk_wiz_10MHz_0 || ORIG_REF_NAME==base_clk_wiz_10MHz_0} -quiet] -quiet

# IP: bd/base/ip/base_concat_interrupts_0/base_concat_interrupts_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_concat_interrupts_0 || ORIG_REF_NAME==base_concat_interrupts_0} -quiet] -quiet

# IP: bd/base/ip/base_ps7_0_0/base_ps7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_ps7_0_0 || ORIG_REF_NAME==base_ps7_0_0} -quiet] -quiet

# IP: bd/base/ip/base_rst_ps7_0_fclk0_0/base_rst_ps7_0_fclk0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_rst_ps7_0_fclk0_0 || ORIG_REF_NAME==base_rst_ps7_0_fclk0_0} -quiet] -quiet

# IP: bd/base/ip/base_switches_gpio_0/base_switches_gpio_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_switches_gpio_0 || ORIG_REF_NAME==base_switches_gpio_0} -quiet] -quiet

# IP: bd/base/ip/base_system_interrupts_0/base_system_interrupts_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_system_interrupts_0 || ORIG_REF_NAME==base_system_interrupts_0} -quiet] -quiet

# IP: bd/base/ip/base_xlconcat_0_1/base_xlconcat_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_xlconcat_0_1 || ORIG_REF_NAME==base_xlconcat_0_1} -quiet] -quiet

# IP: bd/base/ip/base_mux_vector_0_0/base_mux_vector_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mux_vector_0_0 || ORIG_REF_NAME==base_mux_vector_0_0} -quiet] -quiet

# IP: bd/base/ip/base_axi_gpio_0_0/base_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_axi_gpio_0_0 || ORIG_REF_NAME==base_axi_gpio_0_0} -quiet] -quiet

# IP: bd/base/ip/base_rst_ps7_0_100M_1/base_rst_ps7_0_100M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_rst_ps7_0_100M_1 || ORIG_REF_NAME==base_rst_ps7_0_100M_1} -quiet] -quiet

# IP: G:/Vivado/Pynq_file/PYNQ-master/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_i2s_receiver_0_0/base_i2s_receiver_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_i2s_receiver_0_0 || ORIG_REF_NAME==base_i2s_receiver_0_0} -quiet] -quiet

# IP: G:/Vivado/Pynq_file/PYNQ-master/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_i2s_transmitter_0_0/base_i2s_transmitter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_i2s_transmitter_0_0 || ORIG_REF_NAME==base_i2s_transmitter_0_0} -quiet] -quiet

# IP: G:/Vivado/Pynq_file/PYNQ-master/boards/Pynq-Z2/base/Audio_video test_1/Audio_video test_1.srcs/sources_1/bd/base/ip/base_mux_vector_0_1/base_mux_vector_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mux_vector_0_1 || ORIG_REF_NAME==base_mux_vector_0_1} -quiet] -quiet

# IP: G:/Vivado/Pynq_file/PYNQ-master/boards/Pynq-Z2/base/Audio_video test_1/Audio_video test_1.srcs/sources_1/bd/base/ip/base_bclk_mux_0/base_bclk_mux_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_bclk_mux_0 || ORIG_REF_NAME==base_bclk_mux_0} -quiet] -quiet

# IP: G:/Vivado/Pynq_file/PYNQ-master/boards/Pynq-Z2/base/Audio_video test_1/Audio_video test_1.srcs/sources_1/bd/base/ip/base_xbar_11/base_xbar_11.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_xbar_11 || ORIG_REF_NAME==base_xbar_11} -quiet] -quiet

# IP: G:/Vivado/Pynq_file/PYNQ-master/boards/Pynq-Z2/base/Audio_video test_1/Audio_video test_1.srcs/sources_1/bd/base/ip/base_ps7_0_axi_periph_2/base_ps7_0_axi_periph_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_ps7_0_axi_periph_2 || ORIG_REF_NAME==base_ps7_0_axi_periph_2} -quiet] -quiet

# IP: bd/base/ip/base_clk_wiz_10MHz_1/base_clk_wiz_10MHz_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_clk_wiz_10MHz_1 || ORIG_REF_NAME==base_clk_wiz_10MHz_1} -quiet] -quiet

# IP: bd/base/ip/base_rst_ps7_0_fclk0_1/base_rst_ps7_0_fclk0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_rst_ps7_0_fclk0_1 || ORIG_REF_NAME==base_rst_ps7_0_fclk0_1} -quiet] -quiet

# IP: bd/base/ip/base_auto_pc_0/base_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_auto_pc_0 || ORIG_REF_NAME==base_auto_pc_0} -quiet] -quiet

# XDC: bd/base/base_ooc.xdc
