# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: G:/Vivado/Pynq_file/PYNQ-master/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_i2s_transmitter_0_0/base_i2s_transmitter_0_0.xci
# IP: The module: 'base_i2s_transmitter_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/Vivado/Pynq_file/PYNQ-master/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_i2s_transmitter_0_0/base_i2s_transmitter_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_i2s_transmitter_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: G:/Vivado/Pynq_file/PYNQ-master/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_i2s_transmitter_0_0/base_i2s_transmitter_0_0.xci
# IP: The module: 'base_i2s_transmitter_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/Vivado/Pynq_file/PYNQ-master/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_i2s_transmitter_0_0/base_i2s_transmitter_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_i2s_transmitter_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
