# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: g:/Vivado/FFT_VIDEO/FFT_VIDEO_2048/FFT_VIDEO_2048.srcs/sources_1/bd/base/ip/base_axi_gpio_0_2/base_axi_gpio_0_2.xci
# IP: The module: 'base_axi_gpio_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/Vivado/FFT_VIDEO/FFT_VIDEO_2048/FFT_VIDEO_2048.srcs/sources_1/bd/base/ip/base_axi_gpio_0_2/base_axi_gpio_0_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_axi_gpio_0_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: g:/Vivado/FFT_VIDEO/FFT_VIDEO_2048/FFT_VIDEO_2048.srcs/sources_1/bd/base/ip/base_axi_gpio_0_2/base_axi_gpio_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_axi_gpio_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: g:/Vivado/FFT_VIDEO/FFT_VIDEO_2048/FFT_VIDEO_2048.srcs/sources_1/bd/base/ip/base_axi_gpio_0_2/base_axi_gpio_0_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_axi_gpio_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: g:/Vivado/FFT_VIDEO/FFT_VIDEO_2048/FFT_VIDEO_2048.srcs/sources_1/bd/base/ip/base_axi_gpio_0_2/base_axi_gpio_0_2.xci
# IP: The module: 'base_axi_gpio_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/Vivado/FFT_VIDEO/FFT_VIDEO_2048/FFT_VIDEO_2048.srcs/sources_1/bd/base/ip/base_axi_gpio_0_2/base_axi_gpio_0_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_axi_gpio_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: g:/Vivado/FFT_VIDEO/FFT_VIDEO_2048/FFT_VIDEO_2048.srcs/sources_1/bd/base/ip/base_axi_gpio_0_2/base_axi_gpio_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_axi_gpio_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: g:/Vivado/FFT_VIDEO/FFT_VIDEO_2048/FFT_VIDEO_2048.srcs/sources_1/bd/base/ip/base_axi_gpio_0_2/base_axi_gpio_0_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_axi_gpio_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
