# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: G:/Vivado/Pynq_file/PYNQ-master/boards/Pynq-Z2/base/Audio_test/Audio_test.srcs/sources_1/bd/base/ip/base_fir_compiler_0_2/base_fir_compiler_0_2.xci
# IP: The module: 'base_fir_compiler_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/Vivado/Pynq_file/PYNQ-master/boards/Pynq-Z2/base/Audio_test/Audio_test.srcs/sources_1/bd/base/ip/base_fir_compiler_0_2/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_fir_compiler_0_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: g:/Vivado/Pynq_file/PYNQ-master/boards/Pynq-Z2/base/Audio_test/Audio_test.srcs/sources_1/bd/base/ip/base_fir_compiler_0_2/base_fir_compiler_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_fir_compiler_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: G:/Vivado/Pynq_file/PYNQ-master/boards/Pynq-Z2/base/Audio_test/Audio_test.srcs/sources_1/bd/base/ip/base_fir_compiler_0_2/base_fir_compiler_0_2.xci
# IP: The module: 'base_fir_compiler_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/Vivado/Pynq_file/PYNQ-master/boards/Pynq-Z2/base/Audio_test/Audio_test.srcs/sources_1/bd/base/ip/base_fir_compiler_0_2/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_fir_compiler_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: g:/Vivado/Pynq_file/PYNQ-master/boards/Pynq-Z2/base/Audio_test/Audio_test.srcs/sources_1/bd/base/ip/base_fir_compiler_0_2/base_fir_compiler_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_fir_compiler_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
