# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constraints/base.xdc

# XDC: new/Timing.xdc

# Block Designs: bd/base/base.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base || ORIG_REF_NAME==base} -quiet] -quiet

# IP: bd/base/ip/base_audio_codec_ctrl_0_0/base_audio_codec_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_audio_codec_ctrl_0_0 || ORIG_REF_NAME==base_audio_codec_ctrl_0_0} -quiet] -quiet

# IP: bd/base/ip/base_ps7_0_0/base_ps7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_ps7_0_0 || ORIG_REF_NAME==base_ps7_0_0} -quiet] -quiet

# IP: bd/base/ip/base_rst_ps7_0_fclk0_0/base_rst_ps7_0_fclk0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_rst_ps7_0_fclk0_0 || ORIG_REF_NAME==base_rst_ps7_0_fclk0_0} -quiet] -quiet

# IP: bd/base/ip/base_xlconcat_0_1/base_xlconcat_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_xlconcat_0_1 || ORIG_REF_NAME==base_xlconcat_0_1} -quiet] -quiet

# IP: bd/base/ip/base_mux_vector_0_0/base_mux_vector_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_mux_vector_0_0 || ORIG_REF_NAME==base_mux_vector_0_0} -quiet] -quiet

# IP: bd/base/ip/base_axi_gpio_0_0/base_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_axi_gpio_0_0 || ORIG_REF_NAME==base_axi_gpio_0_0} -quiet] -quiet

# IP: bd/base/ip/base_clk_wiz_10MHz_1/base_clk_wiz_10MHz_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_clk_wiz_10MHz_1 || ORIG_REF_NAME==base_clk_wiz_10MHz_1} -quiet] -quiet

# IP: bd/base/ip/base_rst_ps7_0_fclk0_1/base_rst_ps7_0_fclk0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_rst_ps7_0_fclk0_1 || ORIG_REF_NAME==base_rst_ps7_0_fclk0_1} -quiet] -quiet

# IP: bd/base/ip/base_AXI_aud_interface_0_upgraded_ipi_0/base_AXI_aud_interface_0_upgraded_ipi_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_AXI_aud_interface_0_upgraded_ipi_0 || ORIG_REF_NAME==base_AXI_aud_interface_0_upgraded_ipi_0} -quiet] -quiet

# IP: bd/base/ip/base_bclk_mux_0/base_bclk_mux_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_bclk_mux_0 || ORIG_REF_NAME==base_bclk_mux_0} -quiet] -quiet

# IP: bd/base/ip/base_lrclk_mux_0/base_lrclk_mux_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_lrclk_mux_0 || ORIG_REF_NAME==base_lrclk_mux_0} -quiet] -quiet

# IP: bd/base/ip/base_Pulse_LED_controller_0_0/base_Pulse_LED_controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_Pulse_LED_controller_0_0 || ORIG_REF_NAME==base_Pulse_LED_controller_0_0} -quiet] -quiet

# IP: bd/base/ip/base_xbar_0/base_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_xbar_0 || ORIG_REF_NAME==base_xbar_0} -quiet] -quiet

# IP: bd/base/ip/base_xfft_0_0/base_xfft_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_xfft_0_0 || ORIG_REF_NAME==base_xfft_0_0} -quiet] -quiet

# IP: bd/base/ip/base_rgb2dvi_0_0/base_rgb2dvi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_rgb2dvi_0_0 || ORIG_REF_NAME==base_rgb2dvi_0_0} -quiet] -quiet

# IP: bd/base/ip/base_HDMI_test_0_0/base_HDMI_test_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_HDMI_test_0_0 || ORIG_REF_NAME==base_HDMI_test_0_0} -quiet] -quiet

# IP: bd/base/ip/base_xlconstant_1_0/base_xlconstant_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_xlconstant_1_0 || ORIG_REF_NAME==base_xlconstant_1_0} -quiet] -quiet

# IP: bd/base/ip/base_i2s_receiver_0_0/base_i2s_receiver_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_i2s_receiver_0_0 || ORIG_REF_NAME==base_i2s_receiver_0_0} -quiet] -quiet

# IP: bd/base/ip/base_i2s_transmitter_0_0/base_i2s_transmitter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_i2s_transmitter_0_0 || ORIG_REF_NAME==base_i2s_transmitter_0_0} -quiet] -quiet

# IP: bd/base/ip/base_ps7_0_axi_periph_0/base_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_ps7_0_axi_periph_0 || ORIG_REF_NAME==base_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/base/ip/base_cordic_0_0/base_cordic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_cordic_0_0 || ORIG_REF_NAME==base_cordic_0_0} -quiet] -quiet

# IP: bd/base/ip/base_Ext_Mod_0_0/base_Ext_Mod_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_Ext_Mod_0_0 || ORIG_REF_NAME==base_Ext_Mod_0_0} -quiet] -quiet

# IP: bd/base/ip/base_FFT_BRAM_0_0/base_FFT_BRAM_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_FFT_BRAM_0_0 || ORIG_REF_NAME==base_FFT_BRAM_0_0} -quiet] -quiet

# IP: bd/base/ip/base_FFT_config_0_0/base_FFT_config_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_FFT_config_0_0 || ORIG_REF_NAME==base_FFT_config_0_0} -quiet] -quiet

# IP: bd/base/ip/base_axi_gpio_0_1/base_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_axi_gpio_0_1 || ORIG_REF_NAME==base_axi_gpio_0_1} -quiet] -quiet

# IP: bd/base/ip/base_xlslice_1_0/base_xlslice_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_xlslice_1_0 || ORIG_REF_NAME==base_xlslice_1_0} -quiet] -quiet

# IP: bd/base/ip/base_xlslice_2_0/base_xlslice_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_xlslice_2_0 || ORIG_REF_NAME==base_xlslice_2_0} -quiet] -quiet

# IP: bd/base/ip/base_axis_data_fifo_0_0/base_axis_data_fifo_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_axis_data_fifo_0_0 || ORIG_REF_NAME==base_axis_data_fifo_0_0} -quiet] -quiet

# IP: bd/base/ip/base_axis_data_fifo_1_0/base_axis_data_fifo_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_axis_data_fifo_1_0 || ORIG_REF_NAME==base_axis_data_fifo_1_0} -quiet] -quiet

# IP: bd/base/ip/base_LR_Stream_2_AXI_I2S_0_0/base_LR_Stream_2_AXI_I2S_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_LR_Stream_2_AXI_I2S_0_0 || ORIG_REF_NAME==base_LR_Stream_2_AXI_I2S_0_0} -quiet] -quiet

# IP: bd/base/ip/base_xlslice_0_0/base_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_xlslice_0_0 || ORIG_REF_NAME==base_xlslice_0_0} -quiet] -quiet

# IP: bd/base/ip/base_xlslice_3_0/base_xlslice_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_xlslice_3_0 || ORIG_REF_NAME==base_xlslice_3_0} -quiet] -quiet

# IP: bd/base/ip/base_Packet_framer_0_0/base_Packet_framer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_Packet_framer_0_0 || ORIG_REF_NAME==base_Packet_framer_0_0} -quiet] -quiet

# IP: bd/base/ip/base_Packet_framer_L_0/base_Packet_framer_L_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_Packet_framer_L_0 || ORIG_REF_NAME==base_Packet_framer_L_0} -quiet] -quiet

# IP: bd/base/ip/base_FFT_L_0/base_FFT_L_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_FFT_L_0 || ORIG_REF_NAME==base_FFT_L_0} -quiet] -quiet

# IP: bd/base/ip/base_util_vector_logic_0_0/base_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_util_vector_logic_0_0 || ORIG_REF_NAME==base_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/base/ip/base_Ext_Mod_L_0/base_Ext_Mod_L_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_Ext_Mod_L_0 || ORIG_REF_NAME==base_Ext_Mod_L_0} -quiet] -quiet

# IP: bd/base/ip/base_cordic_L_0/base_cordic_L_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_cordic_L_0 || ORIG_REF_NAME==base_cordic_L_0} -quiet] -quiet

# IP: bd/base/ip/base_Windowing_0_0/base_Windowing_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_Windowing_0_0 || ORIG_REF_NAME==base_Windowing_0_0} -quiet] -quiet

# IP: bd/base/ip/base_Windowing_0_1/base_Windowing_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_Windowing_0_1 || ORIG_REF_NAME==base_Windowing_0_1} -quiet] -quiet

# IP: bd/base/ip/base_mux_vector_0_2/base_mux_vector_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_mux_vector_0_2 || ORIG_REF_NAME==base_mux_vector_0_2} -quiet] -quiet

# IP: bd/base/ip/base_FFT_L_data_0/base_FFT_L_data_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_FFT_L_data_0 || ORIG_REF_NAME==base_FFT_L_data_0} -quiet] -quiet

# IP: bd/base/ip/base_mux_vector_0_3/base_mux_vector_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_mux_vector_0_3 || ORIG_REF_NAME==base_mux_vector_0_3} -quiet] -quiet

# IP: bd/base/ip/base_FFT_L_last_0/base_FFT_L_last_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_FFT_L_last_0 || ORIG_REF_NAME==base_FFT_L_last_0} -quiet] -quiet

# IP: bd/base/ip/base_FFT_L_last_1/base_FFT_L_last_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_FFT_L_last_1 || ORIG_REF_NAME==base_FFT_L_last_1} -quiet] -quiet

# IP: bd/base/ip/base_FFT_L_last_2/base_FFT_L_last_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_FFT_L_last_2 || ORIG_REF_NAME==base_FFT_L_last_2} -quiet] -quiet

# IP: bd/base/ip/base_axi_gpio_0_2/base_axi_gpio_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_axi_gpio_0_2 || ORIG_REF_NAME==base_axi_gpio_0_2} -quiet] -quiet

# IP: bd/base/ip/base_axis_data_fifo_0_1/base_axis_data_fifo_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_axis_data_fifo_0_1 || ORIG_REF_NAME==base_axis_data_fifo_0_1} -quiet] -quiet

# IP: bd/base/ip/base_CORDIC_FIFO_L_0/base_CORDIC_FIFO_L_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_CORDIC_FIFO_L_0 || ORIG_REF_NAME==base_CORDIC_FIFO_L_0} -quiet] -quiet

# IP: bd/base/ip/base_axi_bram_ctrl_0_0/base_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_axi_bram_ctrl_0_0 || ORIG_REF_NAME==base_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/base/ip/base_xlslice_0_1/base_xlslice_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_xlslice_0_1 || ORIG_REF_NAME==base_xlslice_0_1} -quiet] -quiet

# IP: bd/base/ip/base_BRAM_ADDR_SLICE_0/base_BRAM_ADDR_SLICE_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_BRAM_ADDR_SLICE_0 || ORIG_REF_NAME==base_BRAM_ADDR_SLICE_0} -quiet] -quiet

# IP: bd/base/ip/base_BRAM_DIN_SLICE1_0/base_BRAM_DIN_SLICE1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_BRAM_DIN_SLICE1_0 || ORIG_REF_NAME==base_BRAM_DIN_SLICE1_0} -quiet] -quiet

# IP: bd/base/ip/base_auto_pc_6/base_auto_pc_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_auto_pc_6 || ORIG_REF_NAME==base_auto_pc_6} -quiet] -quiet

# IP: bd/base/ip/base_auto_pc_0/base_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_auto_pc_0 || ORIG_REF_NAME==base_auto_pc_0} -quiet] -quiet

# IP: bd/base/ip/base_auto_pc_1/base_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_auto_pc_1 || ORIG_REF_NAME==base_auto_pc_1} -quiet] -quiet

# IP: bd/base/ip/base_auto_pc_2/base_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_auto_pc_2 || ORIG_REF_NAME==base_auto_pc_2} -quiet] -quiet

# IP: bd/base/ip/base_auto_pc_3/base_auto_pc_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_auto_pc_3 || ORIG_REF_NAME==base_auto_pc_3} -quiet] -quiet

# IP: bd/base/ip/base_auto_pc_4/base_auto_pc_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_auto_pc_4 || ORIG_REF_NAME==base_auto_pc_4} -quiet] -quiet

# IP: bd/base/ip/base_auto_pc_5/base_auto_pc_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_auto_pc_5 || ORIG_REF_NAME==base_auto_pc_5} -quiet] -quiet

# XDC: bd/base/base_ooc.xdc
