# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: g:/Vivado/Pynq_file/PYNQ-master/boards/Pynq-Z2/base/Audio_video test_1/Audio_video test_1.srcs/sources_1/bd/base/ip/base_xbar_11/base_xbar_11.xci
# IP: The module: 'base_xbar_11' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/Vivado/Pynq_file/PYNQ-master/boards/Pynq-Z2/base/Audio_video test_1/Audio_video test_1.srcs/sources_1/bd/base/ip/base_xbar_11/base_xbar_11_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_xbar_11'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: g:/Vivado/Pynq_file/PYNQ-master/boards/Pynq-Z2/base/Audio_video test_1/Audio_video test_1.srcs/sources_1/bd/base/ip/base_xbar_11/base_xbar_11.xci
# IP: The module: 'base_xbar_11' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/Vivado/Pynq_file/PYNQ-master/boards/Pynq-Z2/base/Audio_video test_1/Audio_video test_1.srcs/sources_1/bd/base/ip/base_xbar_11/base_xbar_11_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_xbar_11'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
